### ISSUE TITLE
jupyter notebook: add line wraps for better diff'ing

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#10]
currently, if you want to make a change to the text of the notebook, it's difficult to do any effective diff'ing becasue there are no line breaks in the text. e.g: https://github.com/benvanwerkhoven/kernel_tuner/blame/45ddee4bfdd7b4ddeebd26431c037a8e54996dd9/tutorial/00-Kernel-Tuner-Introduction.ipynb#L548

**Comment by benvanwerkhoven** [comment]
Yeah I noticed this, it's a bit annoying that no end of lines are inserted in the file. So far, I've simply used the Jupyter notebook server to run the notebook and edit it in the browser, but it's hard to see the diff that way. Do you know if there is an option to jupyter that automatically inserts end of lines in the .ipynb file? Adding them by hand or after the fact with some tool is very far from ideal, because running the notebook would mess it up again.

**Comment by jspaaks** [comment]
I know virtually nothing about Jupyter notebooks, unfortunately. However, Google helped me find this https://github.com/jupyter/nbdime. 

Perhaps another solution could be to simply reflow some of the text, for example Geany or Atom can do this. Note that this only makes sense as long as the text is not immediately unlinewrapped when opened as Jupyter Notebook.

**Comment by benvanwerkhoven** [comment]
nbdime looks like a very handy tool. It appears you can even integrate the diffs it produces with git, [see here](https://nbdime.readthedocs.io/en/latest/vcs.html). If we're using such a tool, there is no need to modify the ipynb files themselves. I'll have a look at how to use nbdime when I continue with the tutorial.

Since this means we don't need to change the files that are currently part of this repository, I'm going to close this issue for the time being.
