### ISSUE TITLE
tuning fortran with gcc

### ISSUE THREAD

**Issue by jiskattema** [benvanwerkhoven/kernel_tuner#108]
When tuning a fortran program with the gfortran compiler, i get an error message:
```
....
UnboundLocalError: local variable 'kernel_name' referenced before assignment
```

Patch attached.
[patch.txt](https://github.com/benvanwerkhoven/kernel_tuner/files/5553082/patch.txt)

**Comment by benvanwerkhoven** [comment]
Hi Jisk! Thanks for bringing this up! I was recently running a linter again on different parts of the code. This one came up as well, but I didn't fix it properly it turns out. I've just fixed it in the way you suggested and for me the fortran vector add example is now working again with gfortran. Could you see if it works for you when you checkout the latest version of master?

You can do a ``git clone`` of the repo, then cd into it, and ``pip install -e .`` to make your Python environment use that directory as the installed version of Kernel Tuner. Let me know if that fixes it!

Best,
Ben

**Comment by jiskattema** [comment]
it works, thanks.
