### ISSUE TITLE
consider using Python built-in tempfile module for handling temporary files

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#11]
e.g. 
- [util.py/delete_temp_file](https://github.com/benvanwerkhoven/kernel_tuner/blob/6b53303162ab7a78e1537cbb420be7ad51342551/kernel_tuner/util.py#L27-L33)
- [util.py/get_temp_filename ](https://github.com/benvanwerkhoven/kernel_tuner/blob/6b53303162ab7a78e1537cbb420be7ad51342551/kernel_tuner/util.py#L35-L38)

tempfile docs [here (Python 2.6)](https://docs.python.org/2/library/tempfile.html) and [here (Python 3.6)](https://docs.python.org/3.6/library/tempfile.html)

**Comment by benvanwerkhoven** [comment]
I did not know this existed, sounds good!

When making changes to this, we should make sure that the behavior is unchanged. For example, it is currently so that when an error happens during the compilation or benchmarking of a kernel that all temporary files belonging to that instance are kept in the current working directory. I guess it would even be better to have a 'keep=False' option in tune_kernel to allow the user to control this behavior.

In any case, when tuning a kernel with a lot of options and you run into an unexpected error after a while, it is very important for the user to be able to inspect the kernel code that caused the error.
