### ISSUE TITLE
capitalize grid_size_x, grid_size_y, grid_size_z as per convention

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#12]
If possible, I'd like to capitalize these variable names as per the convention for preprocessor ``define``s. ([code](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/util.py#L173))

**Comment by benvanwerkhoven** [comment]
I disagree with doing this. It really hurts readability and breaks the symmetry with with all the other tunable parameters currently in use, such as "block_size_x" and so on. It's better to regard these as built-in variables that the Kernel Tuner inserts, rather than constants people use in their code.
