### ISSUE TITLE
differentiate detween device and device_index, platform and platform_index

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#15]
[in cuda.py](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/cuda.py#L20) and in [opencl.py](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/opencl.py#L15).

**Comment by benvanwerkhoven** [comment]
I'm not sure what you mean, could you explain a bit?

**Comment by jspaaks** [comment]
Sure. What I propose is to rename the argument ``device`` [here](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/kernel_tuner/cuda.py#L20) to ``device_index`` to avoid confusion with the variable ``dev`` that your get back when you do for example, [this](https://github.com/benvanwerkhoven/kernel_tuner/blob/dc2cbc4ed50b806478e3b1264e9a3be73a405f3d/test/test_cuda_mocked.py#L30). 

And similar for ``platform`` / ``platform_index``.

**Comment by benvanwerkhoven** [comment]
Ah now I see. I know these variables are just indices, but I chose to stick with the naming that is common in CUDA and OpenCL. 

CUDA Runtime:
http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g159587909ffa0791bbe4b40187a4c6bb

OpenCL specification (see clCreateContext):
https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/

CUDA calls this a 'device' and OpenCL calls it a 'device_id'. In PyCuda it's called 'CUDA_DEVICE' and the PyOpenCL documentations just calls it 'device' as well. I just went for 'device' and 'platform' for the user interface, because this way it will be clear to CUDA and OpenCL programmers what we mean by that. We could of course use a different name for these things internally, but I'm not sure that that is a good idea.

I'm also not sure that there will be much confusion of the two. 'device' and 'platform' are only used for a very brief moment to instantiate the device function interface. From that moment onward, only the device function interface is used.

**Comment by jspaaks** [comment]
I think CUDA is [doing it wrong](https://www.google.com/search?site=&tbm=isch&q=you're+doing+it+wrong+meme&oq=you're+doing+it+wrong+meme) when they refer to a ``device`` when really, they're talking about a ``device_index``. Blasphemy, I know, but OpenCL's use of a ``device_id`` indicates I'm right.

Your argument that both ``device`` and ``platform`` are used only briefly is true but besides the point IMHO.

So, how to resolve this... it seems that you (and me) have given the issue ample thought. We do not share the same opinion. However, you are in charge of governing the project. So, keep ``device`` and ``platform`` and  close the issue?

**Comment by benvanwerkhoven** [comment]
I have thought about this some more, but since we are doing GPU programming in Python and both PyCuda and PyOpenCL are using just 'device' and 'platform' I feel it would be wrong to diverge from what seems to be the common practice.
