### ISSUE TITLE
tutorial review by jspaaks

### ISSUE THREAD

**Issue by jspaaks** [benvanwerkhoven/kernel_tuner#4]
I'm collecting some notes here pertaining to the text of the kernel_tuner including its tutorial.

The kernel_tuner code base is currently at: https://github.com/benvanwerkhoven/kernel_tuner/tree/d36feb61eab791e08132051ffefa9458df79ad80

(I'm using GitHub's blame option to be able to refer to specific line numbers in specific commits for .rst files)

1. I would remove https://github.com/benvanwerkhoven/kernel_tuner/blame/d36feb61eab791e08132051ffefa9458df79ad80/README.rst#L47 since you already have #48
1. in [the install section](https://github.com/benvanwerkhoven/kernel_tuner/blame/d36feb61eab791e08132051ffefa9458df79ad80/README.rst#L39-L56), add a reference to [the dependencies section](https://github.com/benvanwerkhoven/kernel_tuner/blame/d36feb61eab791e08132051ffefa9458df79ad80/README.rst#L58-L72) so a user knows what to have installed before attempting to install the tuner itself. Speaking of dependencies, isn;t it just a case of pip install -r requirements.txt? Since that already lists pycuda and pyopencl.
1. my default python is 2.7 for some reason, looks like that results in an error (could have been related to the errors I got below)
1. using virtual env for python3 should make things easier, e.g.
   ```bash
   # use virtualenv to create a python3 virtual environment called .venv-3
   # (needs virtualenv?)
   virtualenv -p python3 .venv-3 
   
   # activate the virtual environment
   . ./.venv-3/bin/activate
   
   # install requirements
   pip install --requirement requirements.txt
   
   # install the tuner itself
   pip install .
   ```
1. code snippet above doesn't work yet, it complains about nvcc not being present, tried to fix with
   ```bash
   sudo apt install nvidia-cuda-toolkit
   ``` 
   (still complains about missing numpy)
   installing CUDA toolkit from repos apparently is not advisable. Get the newest version instead from https://developer.nvidia.com/cuda-downloads
1. (as discussed) remove ``pycuda`` and ``pyopencl`` from [requirements.txt](https://github.com/benvanwerkhoven/kernel_tuner/blob/d36feb61eab791e08132051ffefa9458df79ad80/requirements.txt#L5-L6); possibly introduce them later when the user knows what he/she needs. Maybe also remove the 'devDependencies': ``mock``, ``nose`` and ``pytest``. Possibly use different sets of requirements, e.g. 
   - requirements-testing
   - requirements-opencl
   - requirements-cuda, etc
1. solved install problems as follows:
   ```bash
   # removed python2 entirely
   sudo apt install python3
   sudo apt install python3-pip
   # edited the requirements so it only includes numpy mock nose  pytest
   pip3 install -r requirements.txt --no-cache-dir
   pip3 install .
   ```
1. about the example about heat diffusion: you mention somewhere that 'temperature' is being dispersed, but technically it's 'heat'. You'd need the heat capacity of the material in order to calculate the change in temperature after a change in heat due to dispersion.
1. you use lower case delta to signify a distance (in time and space), AFAICT this should be upper case, the difference being that lower case delta is used to signify an infinitesimal distance, whereas your distance is 1.0 in space, and 0.225 in time.
1. I'd benefit from a graph/schematic explaining x and y, and u at various combinations of x and y  (not sure this is possible in an jupyter notebook). 
1. I'd benefit from a derivation of the diffusion equation (maybe not in the main document but a link to some other document that uses the same symbols).
1. I see you use ``%matplotlib inline`` somewhere. I didn't know this syntax (never worked with notebooks before). Perhaps add a comment that explains it?
1. Depending on the intended audience, maybe provide a quick recap of threads / blocks and why they matter; or point to some of your other material?
1. in ``In[3]`` line ``field[numpy.random.randint(0,nx,size=10), numpy.random.randint(0,ny,size=10)] = 1e3``, I'd break it down, somehting like:
   ```python
   nHotspots = 10
   cols = numpy.random.randint(0,nx,size=nHotSpots)
   rows = numpy.random.randint(0,ny,size=nHotSpots)
   tempHot = 1000.
   tempCold = 1.
   field = numpy.ones((ny, nx)).astype(numpy.float32) * tempCold
   field[rows, cols] = tempHot
   return field
   ```
1. In ``In[7]`` an d elsewhere, you do a ``memcpy_htod``. Maybe good to mention that ``htod`` stands for host to device (I think:)

**Comment by benvanwerkhoven** [comment]
Thanks a lot for checking it out! 

1. Yeah I think that when you have a github account, cloning the repo using the git:// makes it easier to commit back changes if you make any. If you check out using https:// I believe it to me a bit more work to commit and push back stuff. But you're probably right that for most users the https one is enough and the way it is currently written may be confusing. I'll fix it.

2. Good point about referring to the dependencies in the install section, I'll try to clarify the readme a bit. PyCuda and PyOpenCL are actually optional dependencies, that is why they don't appear in requirements.txt. PyCuda requires CUDA to be installed in order to install and if you only want to use the Kernel Tuner for your OpenCL kernels requiring CUDA to be installed would be weird.

3. Most distributions still default to 2.7 for some strange reason idd. What is the error that you get? On a native installation ``pip install`` probably requires sudo rights.

4. The code snippet at 4 looks OK, what is the error that you get? Numpy is included in requirements.txt, so that should be present after executing ``pip install -r requirements.txt``.

5. I'm not sure if installing CUDA through the package manager is the best way to go, because that may be a very old version. It's probably better to go to https://developer.nvidia.com/cuda-downloads and install it manually.

**Comment by benvanwerkhoven** [comment]
6 and 7. I've written an install guide and cleaned up the requirements and the readme. Do you think it's clearer now? 

8. Good point, I'll fix that!

9. Ah ok. That's not what I'm used to, in particular 'delta t' is for as far as I know always used for the length of a timestep. Jisk also did not say anything about that. I'm not sure what to do with this point.

10. I'm not sure what you mean. There are graphs in the notebook that show the values of u in x and y dimensions for the example scenario. Do you mean the location of the u quantities compared to the x,y gridpoints? I'm assuming that the u quantities reside exactly on the x,y points. Or do you mean something else?

11. That's out of the scope of the tutorial. I believe there is a link to the Wikipedia article about the diffusion equation that should be enough. It's already an extremely long introduction. Don't forget that the goal of the tutorial is not to teach physics. This part is just an introduction to actually tuning GPU kernels.

12. Yeah it's pretty common in jupyter notebooks. The % is called a "magic command". It's the only way to get the output from matplotlib embedded in the notebook, otherwise matplotlib outputs to a new window. I'll add a comment explaining it.

13. I think it's a good idea to include short recap.

14. Yeah I tried to keep it short because it's not the goal to teach people Python. You often see tutorials that read in input data or call a blackbox function to generate the input. I don't like blackboxes, but you should basically compare this bit of code with reading input data or a blackbox function. I don't think it's a good idea to make this any bigger than it is. 

15. Yeah good point! I'll fix that.

**Comment by jspaaks** [comment]
I also needed to ``sudo apt install libffi-dev`` for doing any opencl work (well, for pip installing pyopencl). Maybe also do a ```sudo apt install libffi6`` while you're at it (I had it installed already)

**Comment by jspaaks** [comment]
found some more dependencies for opencl (from https://askubuntu.com/questions/850281/opencl-on-ubuntu-16-04-intel-sandy-bridge-cpu)

minimum requirements (for ubuntu based systems):
```bash
# basic opencl dependency
sudo apt install ocl-icd-libopencl1

# opencl header files (needed by pyopencl)
sudo apt install opencl-headers

# opencl linker and compiler
sudo apt install ocl-icd-opencl-dev
```

You probably also want
```bash
# clinfo program to interrogate the host system about its opencl capabilities
sudo apt install clinfo

# not sure what this adds
sudo apt install beignet
```

**Comment by jspaaks** [comment]
installing OpenCL ICD for Intel CPUs notes

```bash
# go to opencl drivers download page
# https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime

# download ubuntu file
# http://registrationcenter-download.intel.com/akdlm/irc_nas/9019/opencl_runtime_16.1.1_x64_ubuntu_6.4.0.25.tgz

# untar
tar -xzvf opencl_runtime_16.1.1_x64_ubuntu_6.4.0.25.tgz

# change directory
cd opencl_runtime_16.1.1_x64_ubuntu_6.4.0.25

# install
./install_GUI.sh

# choose option 
# 'install as root using sudo'

# remove beignet drivers
sudo apt remove beignet 
sudo apt remove beignet-opencl-icd
# (if need be)
sudo rm /etc/OpenCL/vendors/intel-beignet-x86_64-linux-gnu.icd

# install lsb-core
sudo apt install lsb-core
```

**Comment by jspaaks** [comment]
I've think you've decided on most of the points raised above. I realize that it probably wasn;t a good idea to make a list of points in one issue. Let's make new issues if there are any points left unresolved from the current issue.
