### ISSUE TITLE
Running OpenCL tests on Travis

### ISSUE THREAD

**Issue by egpbos** [benvanwerkhoven/kernel_tuner#40]
It seems like this may be possible using certain drivers, see this discussion: https://github.com/JuliaGPU/OpenCL.jl/issues/121

**Comment by felipeZ** [comment]
We can in principle use the [pyopencl](https://anaconda.org/conda-forge/pyopencl) package of conda to install opencl in Travis. The problem is that in *ubuntu* this package *don't install* the [ocl-icd-opencl-dev](https://github.com/OCL-dev/ocl-icd) headers. In *OSX* the conda recipe for pyopencl works OK.

A first solution is introduced again the sudo keyword in Trravis and `apt-get`  the header, but I would prefer that we still have access to the faster docker containers.

**Comment by egpbos** [comment]
Does pip work for installing pyopencl?

**Comment by felipeZ** [comment]
It is not possible to install `pyopencl` with pip. The conda recipe works well but then *opencl* has problems finding the available devices.

**Comment by felipeZ** [comment]
Currently it is not possible to test the example in Travis with ubuntu, but it is possible to run then with OSX.
